# KeyHelp Docker Compatibility - Apache integration
Alias /keyhelp-docker-monitor/ /var/lib/keyhelp/docker-monitor/
<Directory /var/lib/keyhelp/docker-monitor>
    Options -Indexes
    Require all granted
</Directory>

ScriptAlias /keyhelp-docker-api/ /home/keyhelp/www/keyhelp/docker-api/
<Directory /home/keyhelp/www/keyhelp/docker-api>
    Options +ExecCGI -Indexes
    AddHandler cgi-script .cgi
    Require all granted
</Directory>
